### ISSUE TITLE
Connection Reset By Peer

### ISSUE THREAD

**Issue by srtimsina** [eclecticiq/OpenTAXII#144]
Hi All,
I was trying to execute the taxii-discovery schema after installing the OpenTAXII, Gunicorn and Cabby. The taxii-discovery command worked well when the authentication was basic authentication. But I need to setup client key based authentication and I followed the steps [here](https://tech-habit.info/posts/https-cert-based-auth-with-flask-and-gunicorn/) to setup https certs based auth with Gunicorn. I started the OpenTAXII with the following schema.

`gunicorn opentaxii.http:app --bind localhost:9000 --config python:opentaxii.http --keyfile server.key --certfile server.crt --ca-certs ca-crt.pem --cert-reqs 2
`

It looks working fine.

```
(venv) ubuntu@ubuntu:~$ gunicorn opentaxii.http:app --bind localhost:9000 --config python:opentaxii.http --keyfile server.key --certfile server.crt --ca-certs ca-crt.pem --cert-reqs 2

{"api": "opentaxii.persistence.sqldb.SQLDatabaseAPI", "level": "info", "event": "api.initialized", "timestamp": "2019-09-15T14:45:21.339138Z", "logger": "opentaxii.utils"}
{"api": "opentaxii.auth.sqldb.SQLDatabaseAPI", "level": "info", "event": "api.initialized", "timestamp": "2019-09-15T14:45:21.378607Z", "logger": "opentaxii.utils"}
{"level": "info", "event": "opentaxii.server_configured", "timestamp": "2019-09-15T14:45:21.379221Z", "logger": "opentaxii.server"}
{"level": "info", "logger": "gunicorn.error", "timestamp": "2019-09-15T14:45:21.406857Z", "event": "Starting gunicorn 19.9.0"}
{"level": "info", "logger": "gunicorn.error", "timestamp": "2019-09-15T14:45:21.408663Z", "event": "Listening at: https://127.0.0.1:9000 (5464)"}
{"level": "info", "logger": "gunicorn.error", "timestamp": "2019-09-15T14:45:21.408987Z", "event": "Using worker: sync"}
{"level": "info", "logger": "gunicorn.error", "timestamp": "2019-09-15T14:45:21.414845Z", "event": "Booting worker with pid: 5468"}

```
But when i run the discovery schema, it get's into an error.

```
(venv) ubuntu@ubuntu:~$ taxii-discovery --path http://localhost:9000/services/discovery-a --cert client.crt --key client.key
2019-09-15 20:14:35,725 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery-a
2019-09-15 20:14:35,732 ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
Any help and suggestions would be appreciated.

**Comment by srtimsina** [comment]
@traut there are some progress, we are able to setup Nginx and installed server side ssl. We are able to run the discovery schema, it's giving the expected output. But, when trying to run the discovery schema with a client key, cert, it's giving the error.
`taxii-discovery --path https://suryaraj.com:443/services/discovery-a --cert certificate.crt --key private.key
2019-09-23 20:17:33,253 INFO: Sending Discovery_Request to https://suryaraj.com/services/discovery-a
2019-09-23 20:17:33,276 ERROR: HTTP Error: status code 400`

The Nginx config portion should be ok, as it is working fine when we run a test application and try to curl with the client key, cert files.

**Comment by arcsector** [comment]
@srtimsina can you try using libtaxii to discover with the cert/key combo? I have found that it works much better with certs auth.

**Comment by arcsector** [comment]
In addition, that link is for flask bindings with certificate auth; in other words you would use the certificate to CURL to get the JWT, and *then* use the `taxii-discovery` method, like so:

```bash
$ curl --insecure \
>      --cacert ca-crt.pem \
>      --key client.key \
>      --cert client.crt \
>      -d 'username=test&password=test' \
>      http://localhost:9000/management/auth
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxLCJleHAiOjE0Mjc2MzgyMjN9.oKd43j4KR1Ovu8zOtwFdeaKILys_kpl3fAiECclP7_4"
}

$ taxii-discovery --path http://localhost:9000/services/discovery-a \
>                 --header Authorization:'Bearer eyJleHAiOjE0MjY3OTMwOTYsImFsZyI6IkhTMjU2IiwiaWF0IjoxNDI2Nzg1ODk2fQ.eyJ1c2VyX2lkIjoxfQ.YsZIdbrU92dL8j5G8ydVAsdWHXtx371vC0POmXrS3W8'

```

This is shows to be the case [here](https://opentaxii.readthedocs.io/en/stable/auth.html)

**Comment by srtimsina** [comment]
@arcsector , In addition to my 1st comment, following is the error message I can see in the log message of Nginx, I think the below message is because OpenTAXII could not verify the CA's root cert.

Can you please help me with the following information?

From where does the OpenTAXII read the CA's root certificate? In our mutual authentication setup with Nginx, I am able to authenticate after importing the client certificate along with CA's root certificate but in the case of Cabby, taxii-discovery does not work even though we pass the ca_cert parameter in the schema.

It is giving the following error message

> client SSL certificate verify error: (2:unable to get issuer certificate) while reading client request headers, client: 192.168.4.203, server: srtimsina.com, request: "POST /services/discovery-a HTTP/1.1", host: "srtimsina.com"

**Comment by arcsector** [comment]
@srtimsina the issue is that OpenTAXII doesnt validate certs like HTTP does. I'm not even sure how to specify a cert in opentaxii for auth. You would have to do it at the application level if you wanted to use cabby, because thats how cabby exchanges certfiles. Your current integration supports only cert auth at the wsgi level (gunicorn/flask).

Does that make sense? I'll try and explain it this way:

You have 3 layers here:
- OpenTAXII: this is where you should be inputting certs for auth
- Gunicorn: WSGI orchestration tool
- Nginx: Web proxy

Nginx and Gunicorn broker the transaction with OpenTAXII. When you use cabby to send certs, they're not making it past Nginx/Gunicorn because they're designed to take certs at the HTTP level.

I could be wrong about this. Regardless: where are you specifying OpenTAXII to accept cert for auth? Please post your data-configuration yaml file or wherever you're specifying OpenTAXII to accept certfiles as auth.

**Comment by srtimsina** [comment]
@arcsector, Below is the setup config details.

**Below is the content of config.yaml file** 
```
--
domain: "srtimsina.com:9000"

services:
  - id: inbox_a
    type: inbox
    address: /services/inbox-a
    description: Custom Inbox Service Description A
    destination_collection_required: yes
    accept_all_content: yes
    authentication_required: no
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0
      - urn:taxii.mitre.org:protocol:https:1.0

  - id: inbox_b
    type: inbox
    address: /services/inbox-b
    description: Custom Inbox Service Description B
    destination_collection_required: yes
    accept_all_content: no
    authentication_required: yes
    supported_content:
      - urn:stix.mitre.org:xml:1.1.1
      - urn:custom.example.com:json:0.0.1
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0
      - urn:taxii.mitre.org:protocol:https:1.0

  - id: discovery_a
    type: discovery
    address: /services/discovery-a
    description: Custom Discovery Service description
    advertised_services:
      - inbox_a
      - inbox_b
      - discovery_a
      - collection_management_a
      - poll_a
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0
      - urn:taxii.mitre.org:protocol:https:1.0

  - id: collection_management_a
    type: collection_management
    address: /services/collection-management-a
    description: Custom Collection Management Service description
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0
      - urn:taxii.mitre.org:protocol:https:1.0

  - id: poll_a
    type: poll
    address: /services/poll-a
    description: Custom Poll Service description
    subscription_required: no
    max_result_count: 100
    max_result_size: 10
    authentication_required: yes
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0
      - urn:taxii.mitre.org:protocol:https:1.0

collections:
  - name: collection-a
    available: true
    accept_all_content: true
    type: DATA_SET
    service_ids:
      - inbox_a
      - collection_management_a
      - poll_a

  - name: collection-b
    available: true
    accept_all_content: false
    supported_content:
      - urn:stix.mitre.org:xml:1.1.1
    service_ids:
      - inbox_a
      - inbox_b
      - collection_management_a
      - poll_a

  - name: collection-c
    available: true
    accept_all_content: false
    supported_content:
      - urn:stix.mitre.org:xml:1.1.1
      - urn:custom.bindings.com:json:0.0.1
    service_ids:
      - inbox_a
      - collection_management_a
      - poll_a

  - name: col-not-available
    available: false
    service_ids:
      - inbox_b
      - collection_management_a

accounts:
  - username: suryaraj
    password: test
    permissions:
      collection-a: modify
      collection-b: read
      collection-c: read
      collection-xyz: some
  - username: admin
    password: admin
    is_admin: yes
    ca_cert:
    cert_file:
    key_file:
misp:
    url: "https://"
    api: apikey
    verifySSL: True

```
**Below is the contents Nginx config file.**

```
server {
    listen              80;
    listen              443 ssl;
    server_name         srtimsina.com;
    ssl on;

    location / {
	proxy_pass http://192.168.2.78:9000;
}
    ssl_certificate     /etc/nginx/ssl/certificate.crt;
    ssl_certificate_key /etc/nginx/ssl/private.key;
    ssl_client_certificate /etc/nginx/ssl/certificate.crt;
    ssl_trusted_certificate /etc/nginx/ssl/ca_bundle.crt;
    ssl_verify_client on;
    ssl_verify_depth 3;
    error_log    /var/log/nginx/error.log debug;
}

```
**Below is the command to start the OpenTAXII server**

`gunicorn opentaxii.http:app --bind srtimsina.com:9000 --config python:opentaxii.http`

**Below is the discovery schema**

`taxii-discovery --path https://srtimsina.com:443/services/discovery-a --cert certificate.crt --key private.key --ca-cert ca_root.crt`

Please let me know, if anything needs the correction in the above config.
