### ISSUE TITLE
Config file sample connecting to Taxii 2.1

### ISSUE THREAD

**Issue by shubhamcyble** [eclecticiq/OpenTAXII#226]
Hi Team,

I saw recent PR #222  merged for Taxii 2.1 protocol support.
I'm trying to configure the taxii server for same. 

I'm receiving 405 - Method not allowed while I'm trying to connect via a _taxii2client_

I cannot find any relevant docs to configure the server to support Taxii 2.1

Where does one has to update the discovery_url, api_roots and collection details in the defaults.yml and data-configuration.yml?

**Comment by exdolyeg** [comment]
Similar issue, I have been searching for taxii 2.1 documentation.

Given that the standards for taxii 2.1 requires /taxii2 discovery point, I am failing to see how the current sample data-configuration.yml file implements that.

I have setup the experimental taxii2.1 server provided by the team that published the taxii2.1 standard, and was delighted to see that Eclectriciq opentaxii now supports taxii2.1, however the documentation needs to be updated.

Thanks for a great product. Could you say when the updated documentation will be available to help u s setup a taxii2.1 complaint server?

Secondly, can Eclectriciq opentaxii provide both taxii1.1 and taxii2.1 with the same configuration, even by running on different ports?

**Comment by zentavr** [comment]
```
root@stix:~# cat /opt/opentaxii/taxii2/config.yml.template
---
# Ansible managed

auth_api:
    class: opentaxii.auth.sqldb.SQLDatabaseAPI
    parameters:
        create_tables: true
        db_connection: ${A_URL}
        pool_pre_ping: true
        pool_recycle: 600
        pool_size: 10
        secret: hJ8s****************jO7pO
        token_ttl_secs: 36000
domain: stix2.example.com
logging:
    opentaxii: info
    root: info
return_server_error_details: false
support_basic_auth: true
taxii2:
    allow_custom_properties: true
    contact: devops@hq.example.com
    description: TAXII2 Server
    max_content_length: 2048
    persistence_api:
        class: opentaxii.persistence.sqldb.Taxii2SQLDatabaseAPI
        parameters:
            create_tables: true
            db_connection: ${P_URL}
            pool_pre_ping: true
            pool_recycle: 600
            pool_size: 10
    public_discovery: false
    title: Taxii Service
```
