### ISSUE TITLE
Using a more permanent database

### ISSUE THREAD

**Issue by jezkerwin** [EclecticIQ/OpenTAXII#48]
Is there any documentation about how to configure OpenTAXII to use a database rather than SQLite.
I'm looking to 'productionise' OpenTAXII.
Thanks.

**Comment by aukjan** [comment]
Hello, 

Sure you can!  We use Postgresql internally when working with OpenTAXII, all you need is to properly configure the `opentaxii.yml`, by setting the `db_connection` parameter:

```
domain: "test.taxiistand.com"

persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: postgresql://username:P@ssword@db.example.com:5432/databasename
    create_tables: yes

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: postgresql://username:P@ssword@db.example.com:5432/databasename
    create_tables: yes
    secret: SomeNiceSecret

logging:
  opentaxii: info
  root: info
```
