### ISSUE TITLE
postgresql not working to connect to opentaxii keeps failing

### ISSUE THREAD

**Issue by RomanFire1** [EclecticIQ/OpenTAXII#92]
i am running an ubuntu AWS instance and running open taxii in a virtual env on AWS and can't get to get the service to boot up with:
"gunicorn opentaxii.http:app --bind 0.0.0.0:8000"
this has worked before when i had the files and just changed their directories to another volume so data wouldn't be lost.
the config file shows:
```
---

domain: "localhost:9000"
support_basic_auth: yes
save_raw_inbox_messages: yes

persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: postgresql://***USERNAME***:***PASSWORD***@***DB INSTANCE ID***.***AWS_ENDPOINT_ADDRESS***:5432/***DB NAME***
    create_tables: yes

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: postgresql://***USERNAME***:***PASSWORD***@***DB INSTANCE ID***.***AWS_ENDPOINT_ADDRESS***:5432/***DB NAME***
    create_tables: yes
    secret: ***this is not to be seen***

logging:
  opentaxii: info
  root: info

xml_parser_supports_huge_tree: yes

hooks:
```
both of the *db_connection:* were the exact same.
it try's to boot up the dies and says this:

```
[2017-11-30 00:21:45 +0000] [10495] [INFO] Starting gunicorn 19.7.1
[2017-11-30 00:21:45 +0000] [10495] [INFO] Listening at: http://0.0.0.0:8000 (10495)
[2017-11-30 00:21:45 +0000] [10495] [INFO] Using worker: sync
[2017-11-30 00:21:45 +0000] [10500] [INFO] Booting worker with pid: 10500
[2017-11-30 00:21:45 +0000] [10495] [INFO] Shutting down: Master
[2017-11-30 00:21:45 +0000] [10495] [INFO] Reason: Worker failed to boot.
```
it workered just fine with the data file config but now this is broken since i changed the database.
please help i need this fixed soon and i do not know what to do.
